language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-24.0.3
    - android-24
    - extra-android-m2repository
    - extra-android-support
  licenses:
    - android-sdk-license-.+
    - '.+'
before_script:
    - wget http://services.gradle.org/distributions/gradle-2.14.1-bin.zip
    - unzip gradle-2.14.1-bin.zip
    - export GRADLE_HOME=$PWD/gradle-2.14.1
    - export PATH=$GRADLE_HOME/bin:$PATH
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
    - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
